"""
Example script demonstrating VIC regularization usage with Few-Shot Cosine Transformer

This script shows how to train a few-shot model with VIC regularization enabled.
"""

import torch
import argparse


def main():
    """Example of training with VIC regularization"""
    
    print("=" * 60)
    print("Few-Shot Cosine Transformer with VIC Regularization")
    print("Example Training Script")
    print("=" * 60)
    print()
    
    print("This repository now supports ProFONet's VIC regularization!")
    print()
    
    print("VIC (Variance-Invariance-Covariance) Regularization:")
    print("  - Variance Loss: Encourages feature spread")
    print("  - Invariance Loss: Encourages within-class similarity")
    print("  - Covariance Loss: Encourages feature decorrelation")
    print("  - Dynamic Weighting: Automatically balances loss components")
    print()
    
    print("=" * 60)
    print("Example Usage:")
    print("=" * 60)
    print()
    
    print("1. Basic Training (without VIC):")
    print("-" * 60)
    print("python train_test.py \\")
    print("  --method FSCT_cosine \\")
    print("  --dataset miniImagenet \\")
    print("  --backbone ResNet18 \\")
    print("  --n_way 5 --k_shot 5 \\")
    print("  --num_epoch 50")
    print()
    
    print("2. Training with VIC Regularization (Recommended):")
    print("-" * 60)
    print("python train_test.py \\")
    print("  --method FSCT_cosine \\")
    print("  --dataset miniImagenet \\")
    print("  --backbone ResNet18 \\")
    print("  --n_way 5 --k_shot 5 \\")
    print("  --use_vic 1 \\")
    print("  --vic_lambda_v 1.0 \\")
    print("  --vic_lambda_i 1.0 \\")
    print("  --vic_lambda_c 0.04 \\")
    print("  --vic_dynamic_weights 1 \\")
    print("  --num_epoch 50")
    print()
    
    print("3. Training with Custom VIC Weights:")
    print("-" * 60)
    print("python train_test.py \\")
    print("  --method FSCT_cosine \\")
    print("  --dataset CUB \\")
    print("  --backbone Conv4 \\")
    print("  --n_way 5 --k_shot 1 \\")
    print("  --use_vic 1 \\")
    print("  --vic_lambda_v 2.0 \\")
    print("  --vic_lambda_i 1.5 \\")
    print("  --vic_lambda_c 0.05 \\")
    print("  --vic_alpha 0.002")
    print()
    
    print("4. Memory-Efficient Training (for 8GB VRAM GPUs):")
    print("-" * 60)
    print("python train_test.py \\")
    print("  --method FSCT_cosine \\")
    print("  --dataset miniImagenet \\")
    print("  --backbone Conv4 \\")
    print("  --n_way 5 --k_shot 5 \\")
    print("  --n_episode 100 \\")
    print("  --use_vic 1 \\")
    print("  --vic_dynamic_weights 1")
    print()
    
    print("=" * 60)
    print("VIC Hyperparameter Guide:")
    print("=" * 60)
    print()
    print("--use_vic [0|1]")
    print("  Enable VIC regularization (default: 0)")
    print()
    print("--vic_lambda_v [float]")
    print("  Weight for variance loss (default: 1.0)")
    print("  Higher values encourage more feature spread")
    print()
    print("--vic_lambda_i [float]")
    print("  Weight for invariance loss (default: 1.0)")
    print("  Higher values encourage tighter class clusters")
    print()
    print("--vic_lambda_c [float]")
    print("  Weight for covariance loss (default: 0.04)")
    print("  Higher values encourage stronger decorrelation")
    print()
    print("--vic_dynamic_weights [0|1]")
    print("  Use dynamic weight adjustment (default: 1)")
    print("  Automatically balances VIC components during training")
    print()
    print("--vic_alpha [float]")
    print("  Learning rate for dynamic weight updates (default: 0.001)")
    print("  Controls how fast weights adapt")
    print()
    
    print("=" * 60)
    print("Memory Optimization Tips:")
    print("=" * 60)
    print()
    print("For GPUs with limited VRAM (e.g., 8GB):")
    print("  1. Use smaller backbones (Conv4 instead of ResNet34)")
    print("  2. Reduce --n_episode (e.g., 100 instead of 200)")
    print("  3. Use smaller image size (84 instead of 224)")
    print("  4. Enable VIC dynamic weights (adapts automatically)")
    print("  5. Reduce --n_way or --k_shot if needed")
    print()
    
    print("=" * 60)
    print("Expected Improvements with VIC:")
    print("=" * 60)
    print()
    print("VIC regularization typically provides:")
    print("  - More robust feature representations")
    print("  - Better generalization to novel classes")
    print("  - Improved few-shot classification accuracy")
    print("  - More stable training dynamics")
    print()
    print("Recommended to use with dynamic weights enabled for best results.")
    print()
    
    print("=" * 60)
    print("For more details, see:")
    print("  - README.md: Documentation and usage examples")
    print("  - methods/vic_regularization.py: VIC implementation")
    print("  - methods/memory_utils.py: Memory optimization utilities")
    print("=" * 60)


if __name__ == '__main__':
    main()
