#!/bin/bash

# Example script for comparing two model branches using McNemar's test
# This demonstrates how to compare "Branch B" and "Branch T"

echo "=========================================="
echo "McNemar's Test Model Comparison Examples"
echo "=========================================="
echo ""

# ============================================================================
# Example 1: Comparing Branch B (Baseline) and Branch T (Transformer)
# ============================================================================
echo "Example 1: Comparing Branch B (Baseline) vs Branch T (Transformer)"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "python compare_models_mcnemar.py \\"
echo "    --dataset miniImagenet \\"
echo "    --backbone Conv4 \\"
echo "    --method_a CTX_softmax \\"
echo "    --method_b FSCT_cosine \\"
echo "    --checkpoint_a ./checkpoints/branch_b/best_model.tar \\"
echo "    --checkpoint_b ./checkpoints/branch_t/best_model.tar \\"
echo "    --name_a \"Branch B (Baseline)\" \\"
echo "    --name_b \"Branch T (Transformer)\" \\"
echo "    --n_way 5 \\"
echo "    --k_shot 1 \\"
echo "    --n_query 16 \\"
echo "    --test_iter 600 \\"
echo "    --output ./results/branch_b_vs_t.json"
echo ""
echo "Note: This compares a baseline model (Branch B) with a transformer model (Branch T)"
echo "      to determine if there's a statistically significant performance difference."
echo ""
echo "=========================================="
echo ""

# ============================================================================
# Example 2: Comparing Cosine vs Softmax Attention
# ============================================================================
echo "Example 2: Comparing Cosine vs Softmax Attention"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "python compare_models_mcnemar.py \\"
echo "    --dataset miniImagenet \\"
echo "    --backbone Conv4 \\"
echo "    --method_a FSCT_cosine \\"
echo "    --method_b FSCT_softmax \\"
echo "    --checkpoint_dir_a ./checkpoints/miniImagenet/Conv4_FSCT_cosine_5way_1shot \\"
echo "    --checkpoint_dir_b ./checkpoints/miniImagenet/Conv4_FSCT_softmax_5way_1shot \\"
echo "    --name_a \"Cosine Attention\" \\"
echo "    --name_b \"Softmax Attention\" \\"
echo "    --n_way 5 \\"
echo "    --k_shot 1 \\"
echo "    --test_iter 600 \\"
echo "    --output ./results/cosine_vs_softmax.json"
echo ""
echo "Note: Uses checkpoint_dir to auto-detect best_model.tar in each directory."
echo ""
echo "=========================================="
echo ""

# ============================================================================
# Example 3: Quick Comparison (minimal parameters)
# ============================================================================
echo "Example 3: Quick Comparison with Auto-Detection"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "python compare_models_mcnemar.py \\"
echo "    --dataset miniImagenet \\"
echo "    --method_a FSCT_cosine \\"
echo "    --method_b FSCT_softmax \\"
echo "    --checkpoint_dir_a ./checkpoints/model_a \\"
echo "    --checkpoint_dir_b ./checkpoints/model_b"
echo ""
echo "Note: Uses default parameters (5-way 1-shot, 600 episodes)."
echo ""
echo "=========================================="
echo ""

# ============================================================================
# Example 4: 5-shot Setting
# ============================================================================
echo "Example 4: 5-shot Comparison"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "python compare_models_mcnemar.py \\"
echo "    --dataset CUB \\"
echo "    --backbone ResNet18 \\"
echo "    --method_a FSCT_cosine \\"
echo "    --method_b CTX_cosine \\"
echo "    --checkpoint_a ./checkpoints/cub_fsct_5shot.tar \\"
echo "    --checkpoint_b ./checkpoints/cub_ctx_5shot.tar \\"
echo "    --name_a \"FSCT (5-shot)\" \\"
echo "    --name_b \"CTX (5-shot)\" \\"
echo "    --n_way 5 \\"
echo "    --k_shot 5 \\"
echo "    --test_iter 600"
echo ""
echo "Note: Comparing models on 5-shot tasks."
echo ""
echo "=========================================="
echo ""

# ============================================================================
# Example 5: Medical Dataset (HAM10000)
# ============================================================================
echo "Example 5: Medical Dataset Comparison"
echo "------------------------------------------------------------------------"
echo "Command:"
echo "python compare_models_mcnemar.py \\"
echo "    --dataset HAM10000 \\"
echo "    --backbone Conv4 \\"
echo "    --method_a FSCT_cosine \\"
echo "    --method_b CTX_softmax \\"
echo "    --checkpoint_a ./medical_models/fsct_ham.tar \\"
echo "    --checkpoint_b ./medical_models/ctx_ham.tar \\"
echo "    --name_a \"FSCT on HAM10000\" \\"
echo "    --name_b \"CTX on HAM10000\" \\"
echo "    --n_way 7 \\"
echo "    --k_shot 5 \\"
echo "    --test_iter 600 \\"
echo "    --output ./results/ham10000_comparison.json"
echo ""
echo "Note: 7-way classification for skin lesion types."
echo ""
echo "=========================================="
echo ""

echo "To run any of these examples:"
echo "1. Make this script executable (if needed): chmod +x examples_mcnemar_comparison.sh"
echo "2. Ensure you have the required checkpoint files"
echo "3. Copy the command and paste it in your terminal"
echo "4. Adjust paths as needed for your setup"
echo "5. Results will be saved to the specified output path"
echo ""
echo "For more information, see MCNEMAR_COMPARISON_GUIDE.md"
echo ""
