#!/bin/bash
# Example training script for Hybrid FS-CT + ProFONet
# This script demonstrates various configurations for different scenarios

echo "=========================================="
echo "Hybrid FS-CT + ProFONet Training Examples"
echo "=========================================="
echo ""

# Configuration 1: Basic FS-CT with VIC regularization
echo "Configuration 1: Basic FS-CT + VIC"
echo "----------------------------------"
echo "Command:"
echo "python train.py \\"
echo "  --method FSCT_cosine \\"
echo "  --dataset miniImagenet \\"
echo "  --backbone ResNet18 \\"
echo "  --n_way 5 \\"
echo "  --k_shot 5 \\"
echo "  --n_query 16 \\"
echo "  --use_vic 1 \\"
echo "  --num_epoch 50"
echo ""
echo "Memory: ~8-10GB VRAM"
echo "Expected improvement: +5-10% over baseline"
echo ""

# Configuration 2: Memory-optimized for 16GB VRAM
echo "Configuration 2: Memory-Optimized (16GB VRAM)"
echo "----------------------------------------------"
echo "Command:"
echo "python train.py \\"
echo "  --method FSCT_cosine \\"
echo "  --dataset miniImagenet \\"
echo "  --backbone ResNet18 \\"
echo "  --n_way 5 \\"
echo "  --k_shot 5 \\"
echo "  --n_query 10 \\"
echo "  --use_vic 1 \\"
echo "  --mixed_precision 1 \\"
echo "  --gradient_checkpointing 1 \\"
echo "  --gradient_clip 1.0 \\"
echo "  --num_epoch 50"
echo ""
echo "Memory: ~6-8GB VRAM (40% reduction)"
echo "Training speed: ~15% slower due to checkpointing"
echo ""

# Configuration 3: Lightweight for limited GPU
echo "Configuration 3: Lightweight (8GB VRAM)"
echo "---------------------------------------"
echo "Command:"
echo "python train.py \\"
echo "  --method FSCT_cosine \\"
echo "  --dataset miniImagenet \\"
echo "  --backbone Conv6 \\"
echo "  --n_way 5 \\"
echo "  --k_shot 5 \\"
echo "  --n_query 10 \\"
echo "  --use_vic 1 \\"
echo "  --mixed_precision 1 \\"
echo "  --num_epoch 50"
echo ""
echo "Memory: ~4-6GB VRAM"
echo "Note: Conv6 backbone is lighter than ResNet"
echo ""

# Configuration 4: High-performance for powerful GPU
echo "Configuration 4: High-Performance (24GB+ VRAM)"
echo "-----------------------------------------------"
echo "Command:"
echo "python train.py \\"
echo "  --method FSCT_cosine \\"
echo "  --dataset miniImagenet \\"
echo "  --backbone ResNet34 \\"
echo "  --FETI 1 \\"
echo "  --n_way 5 \\"
echo "  --k_shot 5 \\"
echo "  --n_query 16 \\"
echo "  --use_vic 1 \\"
echo "  --mixed_precision 1 \\"
echo "  --num_epoch 50"
echo ""
echo "Memory: ~12-16GB VRAM"
echo "Expected: Best accuracy with FETI pre-training"
echo ""

# Configuration 5: Custom VIC weights
echo "Configuration 5: Custom VIC Weights"
echo "-----------------------------------"
echo "Command:"
echo "python train.py \\"
echo "  --method FSCT_cosine \\"
echo "  --dataset miniImagenet \\"
echo "  --backbone ResNet18 \\"
echo "  --n_way 5 \\"
echo "  --k_shot 5 \\"
echo "  --use_vic 1 \\"
echo "  --lambda_V_base 0.7 \\"
echo "  --lambda_I 9.0 \\"
echo "  --lambda_C_base 0.3 \\"
echo "  --vic_gamma 1.2 \\"
echo "  --num_epoch 50"
echo ""
echo "Use this to experiment with different VIC weights"
echo ""

# Configuration 6: Testing without VIC (baseline)
echo "Configuration 6: Baseline (No VIC)"
echo "----------------------------------"
echo "Command:"
echo "python train.py \\"
echo "  --method FSCT_cosine \\"
echo "  --dataset miniImagenet \\"
echo "  --backbone ResNet18 \\"
echo "  --n_way 5 \\"
echo "  --k_shot 5 \\"
echo "  --use_vic 0 \\"
echo "  --num_epoch 50"
echo ""
echo "Use this to compare against VIC-enhanced version"
echo ""

echo "=========================================="
echo "VIC Regularization Parameters:"
echo "=========================================="
echo ""
echo "--use_vic [0|1]           : Enable VIC regularization (default: 0)"
echo "--lambda_V_base [float]   : Base variance weight (default: 0.5)"
echo "--lambda_I [float]        : Invariance weight (default: 9.0)"
echo "--lambda_C_base [float]   : Base covariance weight (default: 0.5)"
echo "--vic_gamma [float]       : Variance gamma (default: 1.0)"
echo "--vic_epsilon [float]     : Variance epsilon (default: 1e-6)"
echo ""
echo "Memory Optimization Parameters:"
echo "=========================================="
echo ""
echo "--mixed_precision [0|1]       : Use FP16 training (default: 0)"
echo "--gradient_checkpointing [0|1]: Use gradient checkpointing (default: 0)"
echo "--gradient_clip [float]       : Gradient clipping norm (default: 1.0)"
echo ""
echo "See HYBRID_FSCT_PROFONET.md for detailed documentation"
echo ""
